[package]
name = "blockot"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
godot = { git = "https://github.com/godot-rust/gdext", tag = "v0.4.5" }

[profile.release]
lto = true
opt-level = 3
